menu:
  # Work: /work
  Articles: /articles
  # Musings: /musings

widgets:
- search
- category
- tag
- twitter

excerpt_link:

github:
  username: jboshers

twitter:
  username:
  show_replies: false
  tweet_count: 5

talks:
  - [ Nodevember 2014, Use a Task Runner Already!, https://www.youtube.com/watch?v=7JJGtTzIv7k ]

publications:
  - [ Six Revisions, The Crowdsourcing Quagmire, http://sixrevisions.com/project-management/the-crowdsourcing-quagmire/]
  - [ One Xtra Pixel, Tactics on Selling, http://www.onextrapixel.com/2010/05/25/tactics-on-selling-the-hard-sell-and-the-soft-sell/]

google_analytics:
domain:

feed:
  type: atom
  path: atom.xml
  limit: 10
